### ISSUE TITLE
Handle empty cucumber.json report and not fail workflow run

### ISSUE THREAD

**Issue by sunnyoswalcro** [deblockt/cucumber-report-annotations-action#36]
+ Test is producing empty cucumber.json

# Action
```
- uses: deblockt/cucumber-report-annotations-action@v1.9
        if: always()
        with:
          name: TEST-REPORT-${{ matrix['tests'] }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber.json"
```

# Action logs
```
Run deblockt/cucumber-report-annotations-action@v1.9
  with:
    name: TEST-REPORT-xxx
    access-token: ***
    path: **/cucumber.json
    check-status-on-error: failure
    check-status-on-undefined: success
    check-status-on-pending: success
    annotation-status-on-error: failure
    show-number-of-error-on-check-title: true
start to read cucumber logs using path **/cucumber.json
found cucumber report /runner/_work/xx/xx/xx/xx/build/cucumber/cucumber.json

/runner/_work/_actions/deblockt/cucumber-report-annotations-action/v1.9/webpack:/cucumber-report-annotations-action/reportReader.js:[6](https://github.com/xx/xx/runs/xx?check_suite_focus=true#step:6:6)
        .reduce((a, b) => sum(a, b));
^
TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.module.exports.globalInformation (/runner/_work/_actions/deblockt/cucumber-report-annotations-action/v1.9/webpack:/cucumber-report-annotations-action/reportReader.js:6:1)
    at /runner/_work/_actions/deblockt/cucumber-report-annotations-action/v1.9/webpack:/cucumber-report-annotations-action/index.js:[8](https://github.com/xx/xx/runs/xx?check_suite_focus=true#step:6:8)8:1
```

# Expected
+ Action step doesn't fail
