### ISSUE TITLE
Getting `HttpError: You must authenticate via a GitHub App` during the run

### ISSUE THREAD

**Issue by v-karbovnichy** [deblockt/cucumber-report-annotations-action#40]
I am trying to get this action working, and getting various errors.
The blocking one is `HttpError: You must authenticate via a GitHub App`
I tried to use 2 different tokens, both did not work.

This is my action setup:
```
      - name: Put test run details to GitHub Job annotations
        uses: deblockt/cucumber-report-annotations-action@v1.9
        if: always() && steps.integration-test.outcome != 'skipped'
        with:
          access-token: ${{ secrets.CUCUMBER_ANNOTATIONS_TOKEN }}
          path: "**/cucumber-report.json"
```

GH job log:
```
Run deblockt/cucumber-report-annotations-action@v1.9
  with:
    access-token: ***
    path: **/cucumber-report.json
    check-status-on-error: failure
    check-status-on-undefined: success
    check-status-on-pending: success
    annotation-status-on-error: failure
    show-number-of-error-on-check-title: true
    name: Cucumber report

start to read cucumber logs using path **/cucumber-report.json
found cucumber report /home/runner/work/pulse-alp/pulse-alp/integration-test/build/cucumber-report.json
Creating summary:     [3](https://github.com/trilogy-group/pulse-alp/runs/8093899549?check_suite_focus=true#step:15:3) Scenarios (1 failed, 2 passed)
    5[4](https://github.com/trilogy-group/pulse-alp/runs/8093899549?check_suite_focus=true#step:15:4) Steps (1 failed, [5](https://github.com/trilogy-group/pulse-alp/runs/8093899549?check_suite_focus=true#step:15:5) skipped, 48 passed)
Sending cucumber annotations
HttpError: You must authenticate via a GitHub App.
    at /home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.9/webpack:/cucumber-report-annotations-action/node_modules/@octokit/request/dist-node/index.js:8[6](https://github.com/trilogy-group/pulse-alp/runs/8093899549?check_suite_focus=true#step:15:6):1
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/trilogy-group/pulse-alp/runs/8093899549?check_suite_focus=true#step:15:9)6:5)
    at /home/runner/work/_actions/deblockt/cucumber-report-annotations-action/v1.9/webpack:/cucumber-report-annotations-action/index.js:[16](https://github.com/trilogy-group/pulse-alp/runs/8093899549?check_suite_focus=true#step:15:16)4:1
```
last used token has `repo:*` and `workflow` scopes:
![image](https://user-images.githubusercontent.com/7301634/187469238-81ad4642-af78-4bec-97be-541dcc866ebf.png)

Can you please advise what can I fix here?
