### ISSUE TITLE
Cucumber Report to Annotations is not running in GitHub Action workflow

### ISSUE THREAD

**Issue by smtripathi99** [deblockt/cucumber-report-annotations-action#57]
node.js.yml

```
    - run: npm test
    - name: Cucumber Report to Annotations
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: '**/cucumber-report/cucumber-json/*.json'
```

Run deblockt/cucumber-report-annotations-action@v1.7
  with:
    access-token: ***
    path: ./cucumber-report/cucumber-json/*.json
    check-status-on-error: failure
    check-status-on-undefined: success
    check-status-on-pending: success
    annotation-status-on-error: failure
    show-number-of-error-on-check-title: true
    name: Cucumber report
start to read cucumber logs using path ./cucumber-report/cucumber-json/*.json

**Comment by deblockt** [comment]
Hi, 

Reading you logs, it seem that the step `run: npm test` fail, this is not due to `deblockt/cucumber-report-annotations-action` action. 
I think that `npm test` command return exit code `1` when test fail. 
If you want to continue job execution when test fails, you have many solutions: 
``` yml
 - run: npm test || true
```
or 
``` yml
 - run: npm test
    continue-on-error: true
```
or
```
 -  id: cucumberTests 
    run: npm test
-  name: Cucumber Report to Annotations
    if: ${{ failure() && steps.cucumberTests.outcome == 'failure'}}
    uses: deblockt/cucumber-report-annotations-action@v1.7
    with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: '**/cucumber-report/cucumber-json/*.json'
```

If this is not the case, can you run your action using debug mode, and send logs of `cucumber-report-annotations-action` action.
